###
GET http://localhost:3001/api/persons/693e007310cf4bf753559596

###
GET http://localhost:3001/api/persons/invalidId

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": "12345"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": "12345678"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": "1-2345678"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test2",
    "number": "12-2345"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test3",
    "number": "123-23456"
}

###
DELETE http://localhost:3001/api/persons/6941b2c8797e70203f841e8a


###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "test2"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "number": "12345"
}